### PR TITLE
Add NWB as a Data object

### PR DESCRIPTION
**Pull request by h-mayorquin**
Re-open from #25

Hi guys,here is a draft of ingestion to nwb. After taking a look at the subject data I think it will be easier long-term to add an object that will allow operate on your BaseData object with nwbfile.

This PR is a first attempt at it and more gearted towards discussion and to pose some questions that I have in their proper context.

The overall goal is to an object that behaves as your BaseData and, and behave in the same way as your BaseData (at least with your current methods).

I have some questions that I will start writing but the first one is:
Wher can I get an example of how a protocol object looks like.

I know how the configuration looks like:
https://github.com/ClandininLab/labpack/blob/c945c5c5a71c2ae95df837e362bc08e4caf2ecf8/configs/example_config.yaml#L1-L53

And have some idea of how the subject metadata look like:
https://github.com/h-mayorquin/stimpack/blob/89a326fcfc218b17bfaae3420ac9f9bf711b58d9/src/stimpack/experiment/gui.py#L733-L740

But for the protocol I could not find anything

Also, another question that I have, in this format, do the series_001, series_002` correspond to different experimental sessions? Or are they just different time series (multdimensional of data) for the same experiment?

### CODE REVIEW

**Comment by mhturner** [comment]
This looks like a great direction to go in.

You can see the class definition for a simple example protocol object here: https://github.com/ClandininLab/stimpack/blob/4f39fd615aa9d97e78233aec3296929640fe3c86/stimpack/experiment/protocol.py#L583 and see also its parent class. Basically these things have attributes corresponding to stimulus parameters. For an epoch run (a collection of trials), there are:
- run_parameters: high-level parameters that apply to the run, like pre_time, stim_time, idle_color etc
- protocol_parameters: the parameters entered in the GUI by the user for this run

And for each single trial/epoch there is:
- epoch_stim_parameters: the actual dictionary that gets sent to the stimulus rendering server
- epoch_protocol_parameters: the dictionary of protocol parameters for this single trial, defined by the protocol class


To your second question: series_001 corresponds to an experimental session. But two series may be from the same animal. A single series corresponds to an epoch_run from stimpack.

**Comment by h-mayorquin** [comment]
This should be ready to the extent that is possible.
This imitates your base class to the extent that is described in the same file. That is, I have tested all the methods there and they are the analogous in nwb to your base class. You can check how it looks in the following pen:

https://codepen.io/Heberto-Mayorquin/pen/qBgpjQb

There, I ran your base class and the one that I created to verify that you can create an experimental session, a subject, an epoch run and an epoch.

Let me know when you have time to check it out and possibly test it. 
Also, if you are up to, maybe we can have a second meeting where I explain this in a call if that is easier to you.

**Comment by mhturner** [comment]
Merging this into a new branch...

**Comment by h-mayorquin** [comment]
Let me know if we can offer support. Also, if you find things on the format that are complicated or you think could be better please don't hesistate to say. We have contact with the mantainers of the format and we are always looking for feeddback.

**Pull request merged**
